# Generated by Django 5.2 on 2025-04-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0002_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.IntegerField(default=True),
        ),
    ]
