# Generated by Django 5.2 on 2025-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0005_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
